services:
    _defaults:
        autowire: true
        autoconfigure: true

    MacharaM\Tests\:
        resource: '../../../../tests/*'
 
    MacharaM\Tests\Shared\Infrastructure\Behat\:
        resource: '../../../../src/shared/infrastructure/Behat/*'
