framework:
    test: true

services:
    _defaults:
        autowire: true
        autoconfigure: true

    MacharaM\Tests\:
        resource: '../../../../tests/*'

    MacharaM\Shared\Domain\RandomNumberGeneratorInterface: '@MacharaM\Tests\src\Shared\Infrastructure\ConstantRandomNumberGenerator'
