services:
    _defaults:
        autowire: true
        autoconfigure: true

    MacharaM\Tests\Behat\:
        resource: '../../../../tests/Behat/*'
    
    MacharaM\Tests\Shared\Infrastructure\Behat\:
        resource: '../../../../src/shared/infrastructure/Behat/*'
