framework:
    test: true

services:
    _defaults:
        autowire: true
        autoconfigure: true

    MacharaM\Tests\:
        resource: '../../../../tests/src/*'

    MacharaM\Shared\Domain\RandomNumberGeneratorInterface: '@MacharaM\Tests\Shared\Infrastructure\ConstantRandomNumberGenerator'
