backoffice_backend:
    suites:
        health_check_b:
            paths: [ apps/backoffice/backend/features/health_check ]
            contexts:
                - MacharaM\Tests\Shared\Infrastructure\Behat\ApiContext
    extensions:
        FriendsOfBehat\SymfonyExtension: 
            bootstrap: ~
            kernel:
                class: MacharaM\Backoffice\Backend\BackofficeKernel
                environment: ~
                debug: ~

        Behat\MinkExtension:
            sessions:
                symfony:
                    symfony: ~
            base_url: ''